### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by honzajavorek** [honzajavorek/redis-collections#11]
Implement sorting by [SORT](http://redis.io/commands/sort).

**Comment by bbayles** [comment]
Since we serialize values in lists (and keys in dicts, and elements in sets), sorting in Redis probably doesn't make sense.

It's unfortunate to have to [pull everything into Python](https://github.com/honzajavorek/redis-collections/blob/740b45ca5fd5e332124e2410696545bde7b74753/redis_collections/lists.py#L544-L549) to sort, but I don't think we can bend the "sort by external keys" functionality to sort in any sort of sensible way for arbitrary values.

I'm inclined to close this issue. I'm considering adding some other collections that aren't aimed at emulating standard Python types. For those we could restrict keys and/or values. If we get to that I'd keep Redis-side sorting i nmind.

**Comment by honzajavorek** [comment]
Seems reasonable!
