### ISSUE TITLE
Implement DefaultDict

### ISSUE THREAD

**Issue by honzajavorek** [honzajavorek/redis-collections#9]

**Comment by bbayles** [comment]
This is essentially backlogged on #26. `defaultdict(int)` or `defaultdict(lambda: 'UNKNOWN!') are easy to implement, but `defaultdict(list)` or `defaultdict(dict)`, etc. would not work because of the issue described there.

In [my comment](https://github.com/honzajavorek/redis-collections/issues/26#issuecomment-236079380) I mentioned adding a `writeback` parameter - that we would want to be enabled by default for `DefaultDict`.

**Comment by bbayles** [comment]
Implemented in #46!
